# -*- coding: utf-8 -*-
"""1.Test pro 2. ročník (před FOR).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOTBSVpHi4lT8Oj3erBA-6CdAck4smUW

# 1

Vytvořte aplikaci, do které udělejte tento matematický postup:

* Do x uložte 3.
* Do Y uložte 7.
* Sečtěte tyto dvě proměnné.
* Poté umocněte toto číslo na 2
* Tento výsledek odmocněte druhou mocninou
* Výsdelek vynásobte třema a přičtěte 1

Vypište výsledek a určete, zda je číslo sudé nebo liché.
"""
#TODO
x=3
y=7
a=x+y
a=a**2
a=a**0.5
a=a*3+1
if a%2 == 0:
    print(a)
    print(" cislo je sude")
else:
    print(a)
    print("cislo je liche")


"""**Refereční řešení**
```
Pro x = 3
Pro y = 7
Výsledek je  31.0 liché
```

# 2

Vytvořte program, Do kterého budete zadávat matematické operace.

Napište do programu hlášku: "Vyberte matematickou operaci: 1 pro sčítání a 2 pro odčítání". Pokud uživatel zadá 1, bude zadávat dvě čísla, která se poté sečtou. Pokud 2 tak to samé ale pro rozdíl.
Výsledek vypište ve formátu:

"první +/- druhý = výsledek"
"""
x = int(input("vyber matematickou operaci:"))

if x == 1:
    a=int(input("cislo1:"))
    b=int(input("cislo2:"))
    print(a,"+",b,"=",a+b)
elif x == 2:
    a=int(input("cislo1:"))
    b=int(input("cislo2:"))
    print(a,"-",b,"=",a-b)
else:
    print("spatne cislo")
#TODO

"""**Refereční řešení**
```
Vyberte matematickou operaci: 1 pro sčítání a 2 pro odčítání1
Zadejte první číslo: 5
Zadejte druhé číslo: 7
5 + 7 = 12
```

# 3

Vytvoř program, který požádá uživatele o zadání počtu bodů (0 - 100).

Na základě počtu bodů program přiřadí známku podle těchto pravidel:
* 90 až 100 bodů: "Výborně (1)"
* 75 až 89 bodů: "Chvalitebně (2)"
* 60 až 74 bodů: "Dobře (3)"
* 50 až 59 bodů: "Dostatečně (4)"
* 0 až 49 bodů: "Nedostatečně (5)"

Pokud uživatel zadá číslo mimo rozsah 0-100, program vypíše chybovou hlášku: "Neplatný počet bodů."
"""
a=int(input("zadej pocet bodu:"))
if a<101 and a>89:
    print("vyborne")
elif a<90 and a>74:
    print("chvalitebne")
elif a<75 and a>59:
    print("dobre")
elif a<60 and a>49:
    print("dostatecne")
elif a<50 and a>0:
    print("nedostatecne")
else:
    print("neplatne body")
#TODO

"""**Ukázka řešení**


```
Zadej počet bodů (0-100): 5
Známka: Nedostatečně (5)
```
Nebo


```
Zadej počet bodů (0-100): 73
Známka: Dobře (3)
```

# 4

Vytvořte aplikaci, která bude přijímat tři vstupy uživatele.

* prvním bude výška v cm
* druhý váha v kg
* třetí věk

Vypočítejte mi BMI index pro tyto údaje. BMI = (váha v kg) děleno (výška v metrech na druhou)

Výpis napište ve formátu:

Uživatel ve věku "věk" má BMI: "BMI" což znamená Nadváha/ Podváha atd.

viz hodnoty níže.
* 0 až 18,5: Hodnota podváhy
* 18,5 až 25: Hodnota ideální váhy
* 25 až 30: Hodnota nadváhy
* 30 až 40: Hodnota obezity prvního stupně
* 40 a více: Hodnota těžké obezity
"""
a=int(input("zadejte vysku"))
b=int(input("zadejte vahu"))
b=int(input("zadejte vahu"))

"""
**Refereční řešení**
```
Zadejte vaší výšku v cm.: 187.7
Zadejte vaší váhu v kg.: 55.8
Zadejte vaší věk: 35
Uživatel ve věku 35 má BMI: 15.84 což znamená Podváha
```

"""